### ISSUE TITLE
no grafica las lineas ni tampoco el dataset

### ISSUE THREAD

**Issue by castudil** [Litier/BKTSOM#1]
Este ejemplo incluye 43 neuronas, primero calculo la matriz de adjacencia, luego los vectores de pesos y los clusters. al graficar no salen las lineas.

tampoco puedo graficar el dataset de datos originales, que cargue como "data"

no entiendo cual es el rol de "k" en el llamado de la funcion

#########################
T <- matrix(data = rep(0,43*43),nrow = 43)
T[1,2]<-1
T[2,3]<-1
T[3,4]<-1
T[4,5]<-1
T[4,6]<-1
T[4,7]<-1
T[1,8]<-1
T[8,9]<-1
T[9,10]<-1
T[10,11]<-1
T[10,12]<-1
T[10,13]<-1
T[1,14]<-1
T[14,15]<-1
T[15,16]<-1
T[16,17]<-1
T[16,18]<-1
T[16,19]<-1
T[1,20]<-1
T[20,21]<-1
T[21,22]<-1
T[22,23]<-1
T[22,24]<-1
T[22,25]<-1
T[1,26]<-1
T[26,27]<-1
T[27,28]<-1
T[28,29]<-1
T[28,30]<-1
T[28,31]<-1
T[1,32]<-1
T[32,33]<-1
T[33,34]<-1
T[34,35]<-1
T[34,36]<-1
T[34,37]<-1
T[1,38]<-1
T[38,39]<-1
T[39,40]<-1
T[40,41]<-1
T[40,42]<-1
T[40,43]<-1

W = read.csv("w.csv",header=FALSE)  # read csv file 
data = read.csv("data.csv",header=TRUE)  # read csv file 
head(data)
cluster=rep(1,43)
cluster
graficar(W,1,T,cluster)

**Comment by Litier** [comment]
Arregle la libreria, con la siguiente lineas deberia funcionar sin problema
link para descargar los datos del cluster generado [vectorClustersDatos](https://dl.dropboxusercontent.com/u/78128661/vectorClustersDatos.RData) , se puede generar descomentando las lineas del ultimo For, pero esto es lento
```R
library(devtools)
install_github("Litier/BKTSOM")
library(BKTSOM)
library(ggplot2)

T <- matrix(data = rep(0,43*43),nrow = 43)
T[1,2]<-1
T[2,3]<-1
T[3,4]<-1
T[4,5]<-1
T[4,6]<-1
T[4,7]<-1
T[1,8]<-1
T[8,9]<-1
T[9,10]<-1
T[10,11]<-1
T[10,12]<-1
T[10,13]<-1
T[1,14]<-1
T[14,15]<-1
T[15,16]<-1
T[16,17]<-1
T[16,18]<-1
T[16,19]<-1
T[1,20]<-1
T[20,21]<-1
T[21,22]<-1
T[22,23]<-1
T[22,24]<-1
T[22,25]<-1
T[1,26]<-1
T[26,27]<-1
T[27,28]<-1
T[28,29]<-1
T[28,30]<-1
T[28,31]<-1
T[1,32]<-1
T[32,33]<-1
T[33,34]<-1
T[34,35]<-1
T[34,36]<-1
T[34,37]<-1
T[1,38]<-1
T[38,39]<-1
T[39,40]<-1
T[40,41]<-1
T[40,42]<-1
T[40,43]<-1

W = read.csv("w.csv",header=FALSE) # read csv file
data = read.csv("data.csv",header=TRUE) # read csv file
#head(data)
names(W) <- names(data)

cluster=rep(1,43)

graficarGrafo(W,data,T,cluster)

####################   Ejecucion 2
####################   Con clustering
####################  (es mas lento al tener que calcular los BMU de cada dato)
cluster <- c(1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,4,4,4,4,1,2,1,3,4,1,2,3,1,4,2,4,1,1,4,3,2)
vectorClustersDatos<- rep(1,length(data[,1]))


###  la asignacion del BMU a cada dato es lenta, por eso guarde la que genere yo,
###  pero se puede generar con las siguientes lineas comentadas

#for (i in 1:length(data[,1])){
#  n<- findBMU(data[i,],W)
#  vectorClustersDatos[i] <- cluster[n]
#}

load("vectorClustersDatos.RData")


graficarGrafo(W,data,T,cluster,vectorClustersDatos)
```

**Comment by castudil** [comment]
el orden de los parámetros en la función debería ser los siguientes

1) Conjunto de datos
2) posición de los nodos del grafo
3) matriz de adyacencia que contiene las conexiones del grafo
4) Vector de Clusters

el parámetro 4)  debería ser opcional, esto debido a que no en todos los caso queremos pintar los grupos de distintos colores.

al correr el ejemplo me llama la atención:

i) las conexiones no se graficaron (no aparecen las lineas)
ii) los cluster solo pintan a las neuronas, pero no se pintan los datos del conjunto de entrenamiento. (todos los elementos del dataset aparecen en un mismo color, a pesar que existe mas de un grupo de clusters.)
