### ISSUE TITLE
detalles en la validación y visualizacion

### ISSUE THREAD

**Issue by castudil** [Litier/BKTSOM#4]
1.- los parámetros del SOM están ocultos dentro del método prueba.

 **solución**: parámetros por defecto en la función

2.- division del dataset: en la función la division esta "hardcoded", necesita estar parametrizada (porcentajeTest, el otro se deduce porque suman 100%, aquí debe ser un factor (entre 0.0 y 1.0)).

3.-  escogiste selección con reemplazamiento. error. debe ser seleccion sin reemplazamiento, esto genera dos suconjuntos disjuntos, es decir, ningún elemento se repite. Esto se conoce tecnicamente como una partición.
4.-  graficar el scatterplot del output de la prueba. "salida" es un ¿dataframe? (lista), que entre otras cosas tiene las neuronas y los pesos. En teoría se podría graficar el scatterplot de los datos incluyendo el arbol.  pero no pude.

**solucion**: como es una lista. agrega el árbol

se requiere agregar una línea en el ejemplo que genere el scatterplot después de realizar la validación

5.- incluir un método en c++ para ajustar la semilla seudo aleatoria

```
//Set Seed
void set_seed(int seed){
  srand(seed);
}

```
 llamar a set_seed desde R, incluir en el ejemplo

**Comment by Litier** [comment]
arreglado

**Comment by castudil** [comment]
estos punto se resolvieron, sin embargo a partir de estos adelantos se identificaron una serie de nuevas mejoras y errores que se incluyeron en #5
