### ISSUE TITLE
retoques validacion

### ISSUE THREAD

**Issue by castudil** [Litier/BKTSOM#5]
1 cambiar nombre "prueba" -> "validate"

2 calculateBMUForData -> calculateBMUforEachInstance 
buscar en google "c++ variable name convention"

3 distancia_R: cambiar esto para que sea una tarea realizada en c++

4 linea 17: clusterVector<- c(1:15)
te genera una lista de 15 vecotres, asumiendo que el tamaño del arbol es 15. sin embargo si uno cambia los parametros los nodos ya no seran 15 necesariamente.
solucion: corregir esto para que cree tantos vectores como sea necesario, calculando la cantidad de ndos presentes en el arbol.

5  en clustervisualization, 
la linea
clusterVector[1:7] <- 1
pinta los nodos internos como negros, puesto que estos nodos no participan en la coloracion de las instancias del conjunto de datos analizados.

5.1 este proceso debe llevasrse a cabo dentro de la funcion  de visualziacion
5.2 debe ser general, esto es, debe considerar que distintos arboles tendrán un distinto numero de nodos internos. basicamente el problema aqui es identificar las hojas.

6.- data en estos momentos es una estructura aumentada que involucra el conjunto de datos en informacion adicional, como el id del bmu y las distancias entre la instanci particular y su BMU. se requiere modificar esto apra que, en vez de tener una unica variable agregada, se tienen un a variable para los datos, otra para los vectores de id de bmu y otra para las disntacias, de tal manera que todas ellas estan unidas logicamente, y se pueden acceder,utilizadndo un operador de seleccion de campo.

7.- la visualizacion de clusters: la seleccion de clusters hoy dia se realiza manua,lmente para cada cluster. bvasdicamente se necesita especificar el color de cada nodo para luego pintar las instancias para las que ese nodo es BMU. Hemos pensado una mejora a este modelo, definieindo el id de uno pocos nodos y propagando ese color a través de las ramas del arbol hasta llegar a los hijos.

8.- Investiga como pintar los nodos del arbol con un color especificado por el usuario.

9.- hay una falla con las semillas aleatorias. para indentificar el origen de la falla hay que hacer un experimento extremadamente simple. 

9.1 crear un script en r que llame a srand, y crear una pequeña funcion en ++ que gener 10 numero al azar. si se ejecuta dos veces con las misma semilla deben arrojar los mismo en el entorno R. el problema puede ser que srand no es una variable estatica y por lo tantose pierde su efecto en futuros llamados desde R.

```R
setSeed <- function(semilla=1){
  set_seed(semilla) ## c++
  set.seed(semilla) ## R
}

setSeed(534);

```

9.2 repetir este proceso, pero solo en R. quiere decir setear una semilla en R, y generar 10 valores all azar en R. esta secuencia de valores deberia ser exactamente la mimas en dos ejecucion del script.

**Comment by Litier** [comment]
- [x] 1 terminado
- [ ] 2  falta las variable name convention
- [x] 3 terminado
- [x] 4 terminado
- [ ] 5 Falta terminar
- [x] 6  terminado
- [ ] 7   clustervisualization, propagar el pintado
- [ ] 8  especificar el color
- [x] 9 terminado

Agregue archivos de ejemplo

**Comment by castudil** [comment]
Muchas gracias Javier. Por favor envíame otro mensaje cuando estén todos lo cambios listos y si tienes alguna dificultad técnica, conversemos para ver como resolverlo.
